remote_theme: pmarsceill/just-the-docs
title: AMPEL

collections:
  docs:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    docs:
      name: docs
      nav_exclude: false
      search_exclude: false
