remote_theme: pmarsceill/just-the-docs
title: AMPEL

collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  start:
    permalink: "/start/"
    output: true
  design:
    permalink: "/design/"
    output: true
  interface:
    permalink: "/interface/"
    output: true
  core:
    permalink: "/core/"
    output: true

just_the_docs:
  collections:
    start:
      name: Start
      nav_exclude: false
      search_exclude: false
    design:
      name: Design
      nav_exclude: false
      search_exclude: false
    interface:
      name: Interface
      nav_exclude: false
      search_exclude: false
    core:
      name: Core
      nav_exclude: false
      search_exclude: false
