remote_theme: pmarsceill/just-the-docs
title: AMPEL

collections:
  general:
    permalink: "/:collection/:path"
    output: true
  astronomy:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    general:
      name: general
      nav_exclude: false
      search_exclude: false
    astronomy:
      name: astronomy
      nav_exclude: false
      search_exclude: false
